// Copyright (C) 2026 Dam0k1es, centron5961
//
// This file is part of Crescendo Alarm.
//
// Crescendo Alarm is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Crescendo Alarm is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Crescendo Alarm. If not, see <https://www.gnu.org/licenses/>.

// Ids used below - tests T01 ..., requirements T206-R1 ..., and "requirements"
// section numbers such as b.0 or 8.2 - are defined in
// docs/t206-dst-requirements.md (not docs/TODO.md items: T33 is not T-33).

// docs/TODO.md T-206, docs/timezone-requirements.md TZ-9 (requirements
// b.6): the planning layer against EVERY zone with a transition in
// 2026/2027, with the oracle a checked-in table generated by
// scripts/gen_dst_fixture.dart from `package:timezone`'s own bundled
// database (its version is recorded in the table).
//
// Why that database and not the system tzdata (decided in T-206's
// implementation step): the sweep plans with `package:timezone`'s rules -
// the only way to inject a zone other than the process's own - so its
// expected values must come from the SAME rules source. With a table from
// another database, every zone the two disagree on reads as a planning
// defect: package:timezone 0.11.1 bundles tzdata 2025c, the dev VM had
// 2026c, and nine zones differ (Africa/Casablanca, Africa/El_Aaiun,
// America/Edmonton, America/Vancouver, America/Yellowknife, Canada/Mountain,
// Canada/Pacific, Europe/Chisinau, Europe/Tiraspol). The data cross-check
// below therefore only guards the table against a package upgrade without
// regeneration.
//
// The system tzdata is still compared, informationally: a second table,
// test/fixtures/dst_transitions_2026_2027_system_tzdata.json, from
// scripts/gen_dst_fixture.py (Python `zoneinfo`). Zones whose rules differ
// are REPORTED as a skip reason, not failed - the known limitation recorded
// in docs/TODO.md T-206: a device uses the OPERATING SYSTEM's tzdata, which
// may be newer than the package's, so for those zones this sweep does not
// describe the device's rules. For every zone whose rules agree, the two
// tables' R_plan columns must be identical (red): two brute-force generators
// in two languages, so an algorithm error in either shows.
//
// Independent of the app's ALGORITHM either way: both tables' R_plan values
// come from a brute-force minute scan of TZ-1's definition, not from the
// app's probing and bisection.
//
// Pure layer only, and the result does not depend on the process zone, so
// it runs in CI's UTC leg only - ten identical runs buy nothing. Stated
// limits (G#16): it asserts exact values (T) only for holds, drift gets the
// step bound (G) only; persistence, checkpoint 2 and `deviceOffsetAt` are
// the process-zone tests' job (test/replan_dst_test.dart), in all ten legs.
//
// Regenerate with (from the repository root):
//   dart run scripts/gen_dst_fixture.dart > test/fixtures/dst_transitions_2026_2027.json
//   python3 scripts/gen_dst_fixture.py > test/fixtures/dst_transitions_2026_2027_system_tzdata.json

import 'dart:convert';
import 'dart:io';
import 'dart:math';

import 'package:flutter/material.dart' show TimeOfDay;
import 'package:flutter_test/flutter_test.dart';
import 'package:timezone/data/latest_all.dart' as tzdata;
import 'package:timezone/timezone.dart' as tz;
import 'package:crescendo_alarm/models/scheduling/scheduling_v2.dart';
import 'package:crescendo_alarm/screens/schedule/screen_schedule.dart';

import 'support/zone_rules.dart';

const _fixture = 'test/fixtures/dst_transitions_2026_2027.json';
const _systemFixture =
    'test/fixtures/dst_transitions_2026_2027_system_tzdata.json';
const _minuteMs = 60 * 1000;
const _dayMin = 24 * 60;

final String? _onlyInUtcLeg = Platform.environment['TZ'] == 'UTC'
    ? null
    : 'the sweep is pure and zone-independent: it runs in the TZ=UTC leg only '
        '(requirements b.6)';

class _Transition {
  _Transition(this.zone, Map<String, dynamic> json)
      : tMin = json['t'] as int,
        before = json['before'] as int,
        after = json['after'] as int,
        changeDate = DateTime.parse('${json['changeDate']}T00:00:00Z'),
        rplan = {
          for (final pair in (json['rplan'] as List).cast<List>())
            pair[0] as int: pair[1] as int,
        };

  final String zone;
  final int tMin;
  final int before;
  final int after;
  final DateTime changeDate;

  /// wall minute -> R_plan instant minute.
  final Map<int, int> rplan;

  bool get isGap => after > before;
  int get wallStart => tMin + (isGap ? before : after);
  int get wallEnd => tMin + (isGap ? after : before);

  @override
  String toString() => '$zone ${isGap ? 'gap' : 'overlap'} at '
      '${DateTime.fromMillisecondsSinceEpoch(tMin * _minuteMs, isUtc: true)} '
      '($before -> $after min)';
}

/// The table's own R_plan oracle for zone [zone], at wall minute [w]: the
/// table entry where it has one; else, for a reading outside every affected
/// range (unique), `w - offset` with the offset the table records on its
/// side. A reading inside a range without an entry is a gap in the table
/// and fails loudly rather than being guessed.
int _oracle(List<_Transition> zone, int w) {
  for (final t in zone) {
    final entry = t.rplan[w];
    if (entry != null) return entry;
  }
  for (final t in zone) {
    if (w >= t.wallStart && w < t.wallEnd) {
      throw StateError('no table entry for an affected reading: $t, wall $w');
    }
  }
  var offset = zone.first.before;
  for (final t in zone) {
    if (t.wallEnd <= w) offset = t.after;
  }
  return w - offset;
}

/// The oracle's offset at instant minute [m].
int _offsetAt(List<_Transition> zone, int m) {
  var offset = zone.first.before;
  for (final t in zone) {
    if (t.tMin <= m) offset = t.after;
  }
  return offset;
}

DateTime _instant(int minute) =>
    DateTime.fromMillisecondsSinceEpoch(minute * _minuteMs, isUtc: true);

int _wallMin(DateTime day, int minuteOfDay) =>
    DateTime.utc(day.year, day.month, day.day).millisecondsSinceEpoch ~/
        _minuteMs +
    minuteOfDay;

/// δ of FR-1 on two readings (wall minutes): the time-of-day difference
/// wrapped into (-12 h, +12 h].
int _delta(int from, int to) {
  var d = (to % _dayMin) - (from % _dayMin);
  if (d > _dayMin ~/ 2) d -= _dayMin;
  if (d <= -_dayMin ~/ 2) d += _dayMin;
  return d;
}

/// The data cross-check (requirements b.6): does `package:timezone` have
/// exactly the table's transitions, with the table's offsets, and does every
/// R_plan entry agree with the closed form of its own offsets? Returns the
/// problems per zone (empty list: the zone checks out).
Map<String, List<String>> _crossCheck(Map<String, List<_Transition>> zones) {
  final drift = <String, List<String>>{};
  final from = DateTime.utc(2026).millisecondsSinceEpoch;
  final to = DateTime.utc(2028).millisecondsSinceEpoch;
  for (final entry in zones.entries) {
    final problems = <String>[];
    drift[entry.key] = problems;
    final tz.Location loc;
    try {
      loc = tz.getLocation(entry.key);
    } on tz.LocationNotFoundException {
      problems.add('${entry.key}: not in package:timezone');
      continue;
    }
    int offsetMin(int ms) => loc.timeZone(ms).offset.inMinutes;
    // The package's own transitions, found by an hourly scan.
    final found = <int>[];
    var prev = offsetMin(from);
    for (var ms = from; ms < to; ms += 60 * _minuteMs) {
      final next = offsetMin(ms + 60 * _minuteMs);
      if (next != prev) {
        var lo = ms, hi = ms + 60 * _minuteMs;
        while (hi - lo > _minuteMs) {
          final mid = lo + ((hi - lo) ~/ _minuteMs ~/ 2) * _minuteMs;
          if (offsetMin(mid) == prev) {
            lo = mid;
          } else {
            hi = mid;
          }
        }
        found.add(hi ~/ _minuteMs);
        prev = next;
      }
    }
    final expected = entry.value.map((t) => t.tMin).toList();
    if (found.join(',') != expected.join(',')) {
      problems.add('${entry.key}: package transitions '
          '${found.map(_instant)}, table ${expected.map(_instant)}');
      continue;
    }
    for (final t in entry.value) {
      final ms = t.tMin * _minuteMs;
      if (offsetMin(ms - 1) != t.before || offsetMin(ms) != t.after) {
        problems.add('$t: package offsets ${offsetMin(ms - 1)} -> '
            '${offsetMin(ms)}');
      }
      for (final e in t.rplan.entries) {
        final w = e.key;
        final int closed;
        if (w >= t.wallStart && w < t.wallEnd) {
          closed = !t.isGap
              ? w - t.after // the later occurrence
              : (t.wallEnd ~/ _dayMin > w ~/ _dayMin
                  ? t.tMin - 1 // TZ-2a
                  : t.tMin);
        } else {
          closed = w - (w < t.wallStart ? t.before : t.after);
        }
        if (closed != e.value) {
          problems.add('$t: wall ${_instant(w)} table ${_instant(e.value)}, '
              'closed form ${_instant(closed)}');
        }
      }
    }
  }
  // The other direction: a zone the package changes in 2026/27 that the
  // table does not list at all.
  final packageOnly = <String>[];
  for (final name in tz.timeZoneDatabase.locations.keys) {
    if (zones.containsKey(name)) continue;
    final loc = tz.timeZoneDatabase.locations[name]!;
    final first = loc.timeZone(from).offset;
    for (var ms = from; ms < to; ms += 60 * _minuteMs) {
      if (loc.timeZone(ms).offset != first) {
        packageOnly.add('$name: changes in package:timezone, not in the table');
        break;
      }
    }
  }
  drift['(package only)'] = packageOnly;
  return drift;
}

Map<String, List<_Transition>> _zonesOf(Map<String, dynamic> table) => {
      for (final e in (table['zones'] as Map<String, dynamic>).entries)
        e.key: [
          for (final t in (e.value as List).cast<Map<String, dynamic>>())
            _Transition(e.key, t),
        ],
    };

String _shape(List<_Transition> zone) =>
    zone.map((t) => '${t.tMin}:${t.before}:${t.after}').join(',');

/// The informational comparison with the system tzdata (see the header):
/// the zones whose 2026/27 transitions differ between the two tables, and
/// the R_plan mismatches among the zones that agree.
({List<String> differingZones, List<String> rplanMismatches}) _compareSystem(
    Map<String, List<_Transition>> oracle,
    Map<String, List<_Transition>> system) {
  final differing = <String>[];
  final mismatches = <String>[];
  for (final name in {...oracle.keys, ...system.keys}.toList()..sort()) {
    final a = oracle[name], b = system[name];
    if (a == null || b == null || _shape(a) != _shape(b)) {
      differing.add(name);
      continue;
    }
    for (var i = 0; i < a.length; i++) {
      for (final e in a[i].rplan.entries) {
        if (b[i].rplan[e.key] != e.value) {
          mismatches.add('${a[i]}: wall ${_instant(e.key)} package table '
              '${_instant(e.value)}, system table '
              '${b[i].rplan[e.key] == null ? 'missing' : _instant(b[i].rplan[e.key]!)}');
        }
      }
    }
  }
  return (differingZones: differing, rplanMismatches: mismatches);
}

void main() {
  // Computed at declaration time (UTC leg only) so that a database
  // difference can be REPORTED as a skip reason naming the zones.
  final system = _onlyInUtcLeg != null
      ? null
      : _compareSystem(
          _zonesOf(jsonDecode(File(_fixture).readAsStringSync())
              as Map<String, dynamic>),
          _zonesOf(jsonDecode(File(_systemFixture).readAsStringSync())
              as Map<String, dynamic>));

  late Map<String, dynamic> table;
  late Map<String, List<_Transition>> zones;
  late Map<String, List<String>> drift;

  setUpAll(() {
    tzdata.initializeTimeZones();
    table =
        jsonDecode(File(_fixture).readAsStringSync()) as Map<String, dynamic>;
    zones = _zonesOf(table);
    drift = _crossCheck(zones);
  });

  test(
      'the table is what it claims (its zone and transition counts), is '
      'generated from package:timezone and records its tzdata version', () {
    expect(table['tzdata'], isA<String>());
    expect(table['source'], startsWith('package:timezone '));
    expect(zones.length, table['zoneCount']);
    expect(zones.values.fold<int>(0, (n, z) => n + z.length),
        table['transitionCount']);
    // The TZ-2a zones are in it, with the fallback (requirements 8.4).
    for (final name in [
      'America/Nuuk',
      'America/Godthab',
      'America/Scoresbysund'
    ]) {
      final spring = zones[name]!.first;
      final w = _wallMin(DateTime.utc(2026, 3, 28), 23 * 60 + 30);
      expect(spring.rplan[w], spring.tMin - 1, reason: name);
    }
  }, skip: _onlyInUtcLeg);

  test(
      'data cross-check: package:timezone (the table\'s own source) '
      'reproduces every transition of the table and has no other one in '
      '2026/27 - the table is not stale; every R_plan entry agrees with the '
      'closed form of its own offsets', () {
    final problems = [for (final p in drift.values) ...p];
    expect(problems, isEmpty,
        reason: '${problems.length} problems in '
            '${drift.values.where((p) => p.isNotEmpty).length} zones (table: '
            'tzdata ${table['tzdata']}, vs package:timezone\'s bundled '
            'database); first:\n${problems.take(10).join('\n')}');
  }, skip: _onlyInUtcLeg);

  test(
      'system tzdata (informational): every zone has the same 2026/27 rules '
      'in the operating system\'s database as in package:timezone\'s', () {
    expect(system!.differingZones, isEmpty);
  },
      skip: _onlyInUtcLeg ??
          (system!.differingZones.isEmpty
              ? false
              : 'known limitation (docs/TODO.md T-206), reported, not failed: '
                  '${system.differingZones.length} zones have different '
                  '2026/27 rules in the system tzdata than in '
                  'package:timezone\'s bundled database, so the sweep does '
                  'not describe a device\'s own rules there: '
                  '${system.differingZones.join(', ')}'));

  test(
      'system tzdata: where the two databases agree, the two independently '
      'generated R_plan tables are identical', () {
    expect(system!.rplanMismatches, isEmpty,
        reason: '${system.rplanMismatches.length} mismatches; first:\n'
            '${system.rplanMismatches.take(10).join('\n')}');
  }, skip: _onlyInUtcLeg);

  test('A1: no zone changes its offset twice within 30 hours', () {
    final close = <String>[];
    for (final z in zones.values) {
      for (var i = 1; i < z.length; i++) {
        if (z[i].tMin - z[i - 1].tMin <= 30 * 60) {
          close.add('${z[i - 1]}, ${z[i]}');
        }
      }
    }
    expect(close, isEmpty);
  }, skip: _onlyInUtcLeg);

  test(
      'the sweep: every transition x window position {0, 3, 6} x P - T '
      '(holds are exact), G (steps within maxDailyDelta, no notification on a '
      'hold), S (the upper bound holds)', () {
    final failures = <String>[];
    var plans = 0;
    final rng = Random(206);
    // A zone whose rules differ between the table and package:timezone is
    // reported by the cross-check above (red, by name) and left out here:
    // its plan is made with one database and would be judged by the other.
    final excluded = drift.entries
        .where((e) => e.value.isNotEmpty)
        .map((e) => e.key)
        .toList();
    for (final entry in zones.entries) {
      if (excluded.contains(entry.key)) continue;
      final rules = zoneRules(tz.getLocation(entry.key));
      final zone = entry.value;
      for (final t in zone) {
        final times = <int>{
          7 * 60,
          30,
          for (final w in t.rplan.keys) w % _dayMin,
        };
        for (final k in [0, 3, 6]) {
          final window = List.generate(
              7,
              (i) => DateTime.utc(t.changeDate.year, t.changeDate.month,
                  t.changeDate.day - k + i));
          final anchorDay = DateTime.utc(
              window.first.year, window.first.month, window.first.day - 1);
          for (final p in times) {
            final label = '$t, k $k, P ${p ~/ 60}:${p % 60}';
            final anchorClock = _wallMin(anchorDay, p);
            final anchor = _instant(_oracle(zone, anchorClock));
            final preferred = TimeOfDay(hour: p ~/ 60, minute: p % 60);
            WeekPlanResult plan(
                    {TimeOfDay? preferredTime,
                    List<Meeting> events = const []}) =>
                computeWeekPlan(
                  window: window,
                  lastEffectiveWakeTime: anchor,
                  lastEffectiveClockTime: _instant(anchorClock),
                  allEvents: events,
                  offsetAt: rules,
                  durationToWakeUp: Duration.zero,
                  durationToGetReadyForDay: (_) => Duration.zero,
                  preferredWakeUpTime: preferredTime,
                  maxDailyDelta: const Duration(minutes: 30),
                  gapDayCounter: 0,
                  scheduleOnGapDays: true,
                );

            // Hold (T, and G's "no notification"): P held exactly.
            final hold = plan(preferredTime: preferred);
            plans++;
            for (final day in window) {
              final expected = _instant(_oracle(zone, _wallMin(day, p)));
              if (hold.valuesByDay[day] != expected) {
                failures.add('T $label: $day expected $expected, got '
                    '${hold.valuesByDay[day]}');
              }
            }
            if (hold.overrunNotificationNeeded) {
              failures.add('G $label: a hold raised a notification');
            }

            // Drift (G): towards P + 60 min, planned clock times step by at
            // most maxDailyDelta.
            final drift = plan(
                preferredTime: TimeOfDay(
                    hour: ((p + 60) % _dayMin) ~/ 60, minute: (p + 60) % 60));
            plans++;
            var previous = anchorClock;
            for (final day in window) {
              final clock = drift.plannedClockTimes[day];
              if (clock == null) {
                failures.add('G $label: $day has no planned clock time');
                break;
              }
              final c = clock.millisecondsSinceEpoch ~/ _minuteMs;
              if (_delta(previous, c).abs() > 30) {
                failures.add('G $label: $day steps ${_delta(previous, c)} min');
              }
              previous = c;
            }

            // Appointment (S): one seeded appointment in the window; its day
            // (by the table's rules at its instant) never exceeds it.
            final firstMinute = _oracle(zone, _wallMin(window.first, 0));
            final eventMinute = firstMinute + rng.nextInt(7 * _dayMin);
            final eventWall = eventMinute + _offsetAt(zone, eventMinute);
            final eventDay = DateTime.utc(1970, 1, 1 + eventWall ~/ _dayMin);
            final event = _instant(eventMinute);
            final withEvent = plan(preferredTime: preferred, events: [
              Meeting(
                from: event,
                to: event.add(const Duration(hours: 1)),
                isAllDay: false,
                startTimeZone: 'Etc/UTC',
                endTimeZone: 'Etc/UTC',
              ),
            ]);
            plans++;
            final onDay = window.where((d) => d == eventDay);
            if (onDay.isNotEmpty) {
              final value = withEvent.valuesByDay[onDay.single];
              if (value == null || value.isAfter(event)) {
                failures.add('S $label: appointment $event on $eventDay, value '
                    '$value');
              }
            }
          }
        }
      }
    }
    expect(failures, isEmpty,
        reason: '${failures.length} failures in $plans plans (zones left out '
            'for database drift: $excluded); first:\n'
            '${failures.take(12).join('\n')}');
  }, skip: _onlyInUtcLeg, timeout: const Timeout(Duration(minutes: 5)));
}
