#!/usr/bin/env python3
# Copyright (C) 2026 Dam0k1es, centron5961
#
# This file is part of Crescendo Alarm.
#
# Crescendo Alarm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Crescendo Alarm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Crescendo Alarm. If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Synthesise the bundled alarm tones that have no recorded source (T-212).

`assets/sounds/lollipop.mp3` ("Playful Chime", the default tone) is not a
recording: it is generated by this script, so its complete source is in the
repository and it is licensed GPL-3.0-or-later like the app itself
(assets/sounds/CREDITS.md).

The tone is a two-bar C major pentatonic phrase played by a marimba-like
voice (fundamental plus the bar's characteristic ~4x and ~10x partials, all
decaying exponentially) with a quiet glockenspiel layer an octave above on
the strong beats. It ends on the dominant (G) so the phrase resolves into
its own beginning, because the alarm plugin plays tones in a loop
(`loopAudio: true` in lib/models/alarms/ringing_alarm_settings.dart). The
loop is seamless by construction: the phrase is rendered twice in a row and
the second pass is kept, so every note tail that runs past the end is
already present, wrapped round, at the start of the kept pass.

Only the Python standard library is used to synthesise. The MP3 encoding
step needs ffmpeg with libmp3lame:

    python3 scripts/gen_tones.py            # writes assets/sounds/lollipop.mp3
    python3 scripts/gen_tones.py --wav x.wav  # writes the raw WAV only

The output is deterministic (no randomness), so re-running the script
reproduces the shipped file's audio; the MP3 bytes may still differ between
ffmpeg/LAME versions.
"""
import argparse
import array
import math
import os
import subprocess
import sys
import tempfile
import wave

RATE = 44100
BPM = 120
STEP = 60.0 / BPM / 2  # one eighth note, in seconds
STEPS = 16  # two bars of eighth notes -> a 4.0 s loop

# MIDI note numbers per eighth-note step; None is a rest.
# C5 E5 G5 C6 | - G5 A5 G5 | E5 - D5 E5 | G5 - - -
MELODY = [72, 76, 79, 84, None, 79, 81, 79, 76, None, 74, 76, 79, None, None, None]
# Glockenspiel sparkle (one octave up), only on a few strong steps.
SPARKLE = {0: 84, 3: 96, 6: 93, 12: 91}

# Peak level of the final mix before encoding, in dBFS. Leaves headroom for
# the MP3 encoder's inter-sample overshoot so the true peak stays below
# -1 dBTP.
PEAK_DBFS = -1.5


def midi_hz(note):
    return 440.0 * 2.0 ** ((note - 69) / 12.0)


def marimba(freq, t):
    """One marimba-like strike at time t (seconds since note-on)."""
    if t < 0:
        return 0.0
    attack = min(1.0, t / 0.003)  # 3 ms attack: soft mallet, no click
    w = 2.0 * math.pi * freq * t
    return attack * (
        1.00 * math.exp(-t * 2.4) * math.sin(w)
        + 0.30 * math.exp(-t * 11.0) * math.sin(3.93 * w)
        + 0.06 * math.exp(-t * 30.0) * math.sin(9.95 * w)
    )


def glockenspiel(freq, t):
    """A soft glockenspiel bar: inharmonic partials 1, 2.76, 5.40."""
    if t < 0:
        return 0.0
    attack = min(1.0, t / 0.002)
    w = 2.0 * math.pi * freq * t
    return attack * (
        1.00 * math.exp(-t * 2.2) * math.sin(w)
        + 0.25 * math.exp(-t * 6.0) * math.sin(2.76 * w)
        + 0.08 * math.exp(-t * 14.0) * math.sin(5.40 * w)
    )


def render():
    """Return (left, right) float lists for one seamless loop."""
    loop = int(round(STEPS * STEP * RATE))
    total = 2 * loop
    left = [0.0] * total
    right = [0.0] * total
    tail = int(2.0 * RATE)  # long enough for every partial to decay
    events = []
    for rep in range(2):
        for step, note in enumerate(MELODY):
            if note is not None:
                # Small, fixed stereo spread by pitch: low left, high right.
                pan = 0.5 + (note - 78) / 40.0
                events.append((rep * STEPS + step, marimba, midi_hz(note), 0.85, pan))
        for step, note in SPARKLE.items():
            events.append((rep * STEPS + step, glockenspiel, midi_hz(note), 0.18, 0.5))
    for start_step, voice, freq, gain, pan in events:
        start = int(round(start_step * STEP * RATE))
        gl = gain * math.cos(pan * math.pi / 2)
        gr = gain * math.sin(pan * math.pi / 2)
        for i in range(min(tail, total - start)):
            s = voice(freq, i / RATE)
            left[start + i] += gl * s
            right[start + i] += gr * s
    # Keep the second pass: its start already contains the first pass's tails.
    return left[loop:], right[loop:]


def write_wav(path, left, right):
    peak = max(max(abs(x) for x in left), max(abs(x) for x in right))
    scale = (10 ** (PEAK_DBFS / 20.0)) / peak
    pcm = array.array("h")
    for l, r in zip(left, right):
        pcm.append(int(round(l * scale * 32767)))
        pcm.append(int(round(r * scale * 32767)))
    if sys.byteorder == "big":
        pcm.byteswap()
    with wave.open(path, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(pcm.tobytes())


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--wav", help="write the raw WAV here and stop")
    parser.add_argument(
        "--out",
        default=os.path.join(root, "assets", "sounds", "lollipop.mp3"),
        help="MP3 output path (default: assets/sounds/lollipop.mp3)",
    )
    args = parser.parse_args()
    left, right = render()
    if args.wav:
        write_wav(args.wav, left, right)
        return
    with tempfile.TemporaryDirectory() as tmp:
        wav = os.path.join(tmp, "lollipop.wav")
        write_wav(wav, left, right)
        subprocess.run(
            [
                "ffmpeg", "-v", "error", "-y", "-i", wav,
                "-codec:a", "libmp3lame", "-b:a", "192k",
                "-metadata", "title=Playful Chime",
                "-metadata", "artist=Crescendo Alarm contributors",
                "-metadata", "copyright=GPL-3.0-or-later",
                "-metadata", "comment=Generated by scripts/gen_tones.py",
                args.out,
            ],
            check=True,
        )


if __name__ == "__main__":
    main()
