#!/usr/bin/env python3
# Copyright (C) 2026 Dam0k1es, centron5961
#
# This file is part of Crescendo Alarm.
#
# Crescendo Alarm is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Crescendo Alarm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Crescendo Alarm. If not, see <https://www.gnu.org/licenses/>.

"""docs/TODO.md T-206 (TZ-9, requirements b.6): the SYSTEM-tzdata table for
test/t206_dst_sweep_test.dart's informational cross-check.

For EVERY zone Python's `zoneinfo` knows that changes its UTC offset in
2026/2027, this records each transition (instant, offset before/after) and
R_plan - TZ-1's resolution R with TZ-2a's fallback - for every whole
15-minute reading from one hour before to one hour after the affected range,
plus 07:00 and 00:30 on the change date. Same shape as the oracle table.

Not the sweep's oracle. The sweep plans with `package:timezone`'s rules, so
its expected values come from the same rules source - the table generated by
scripts/gen_dst_fixture.dart. This one is read from the operating system's
tzdata (the database a real device uses, which may be newer than the
package's), and the sweep test compares the two: zones whose rules differ are
REPORTED (a known limitation, docs/TODO.md T-206), and for every zone whose
rules agree the two R_plan columns must be identical - two brute-force
generators in two languages over two databases, so an algorithm error in
either one shows.

Its ALGORITHM is a brute-force minute scan of TZ-1's definition (corrected
2026-09-28): R(w) = min{ t : L(t) >= w and L(s) > w for every s > t }, not
the app's probing and bisection.

Usage:
  python3 scripts/gen_dst_fixture.py > test/fixtures/dst_transitions_2026_2027_system_tzdata.json
"""

import json
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo, available_timezones

UTC = timezone.utc
MINUTE = timedelta(minutes=1)
START = datetime(2026, 1, 1, tzinfo=UTC)
END = datetime(2028, 1, 1, tzinfo=UTC)
EPOCH = datetime(1970, 1, 1)


def reading(t, zone):
    """L(t): the local reading at instant t, naive."""
    return t.astimezone(zone).replace(tzinfo=None)


def minutes(naive_or_aware):
    if naive_or_aware.tzinfo is not None:
        naive_or_aware = naive_or_aware.astimezone(UTC).replace(tzinfo=None)
    return int((naive_or_aware - EPOCH) / MINUTE)


def resolve(w, zone, before, after):
    """TZ-1's R by brute force: of all instants (minute scan over every
    candidate) that show the reading w, the LATER one; if none does (a
    skipped reading), the first instant showing a later reading. That is
    TZ-1's corrected formula `min{ t : L(t) >= w and L(s) > w for every
    s > t }` evaluated directly: the later occurrence at every minute of a
    repeated range, its first minute included (the formula first adopted,
    `min{ t : L(s) >= w for every s >= t }`, gave the first occurrence
    there; docs/timezone-requirements.md TZ-1)."""
    base = w.replace(tzinfo=UTC)
    lo = base - max(before, after) - timedelta(hours=2)
    hi = base - min(before, after) + timedelta(hours=2)
    occurrences = []
    t = lo
    while t <= hi:
        if reading(t, zone) == w:
            occurrences.append(t)
        t += MINUTE
    if occurrences:
        return max(occurrences)
    t = hi
    assert reading(t, zone) >= w
    while reading(t - MINUTE, zone) >= w:
        t -= MINUTE
    return t


def planned(w, zone, before, after):
    """R_plan (TZ-2a): R, or one minute earlier when R reads a later date."""
    r = resolve(w, zone, before, after)
    return r - MINUTE if reading(r, zone).date() > w.date() else r


def transitions(zone):
    out = []
    t = START
    prev = t.astimezone(zone).utcoffset()
    while t < END:
        n = t + timedelta(hours=1)
        off = n.astimezone(zone).utcoffset()
        if off != prev:
            lo, hi = t, n
            while hi - lo > MINUTE:
                mid = lo + timedelta(minutes=((hi - lo) // MINUTE) // 2)
                if mid.astimezone(zone).utcoffset() == prev:
                    lo = mid
                else:
                    hi = mid
            out.append((hi, prev, off))
            prev = off
        t = n
    return out


def tzdata_version():
    for candidate in ("/usr/share/zoneinfo/tzdata.zi",):
        p = Path(candidate)
        if p.exists():
            first = p.read_text().splitlines()[0]
            if first.startswith("# version "):
                return first[len("# version "):].strip()
    try:
        import tzdata  # type: ignore
        return "tzdata package " + tzdata.IANA_VERSION
    except ImportError:
        return "unknown"


def main():
    zones = {}
    count = 0
    for name in sorted(available_timezones()):
        try:
            zone = ZoneInfo(name)
        except Exception:
            continue
        rows = []
        for t, before, after in transitions(zone):
            assert before.total_seconds() % 60 == 0 and after.total_seconds() % 60 == 0
            gap = after > before
            start = (t + before if gap else t + after).replace(tzinfo=None)
            end = (t + after if gap else t + before).replace(tzinfo=None)
            change_date = start.date()
            readings = set()
            w = (start - timedelta(hours=1)).replace(second=0, microsecond=0)
            w -= timedelta(minutes=w.minute % 15)
            while w <= end + timedelta(hours=1):
                readings.add(w)
                w += timedelta(minutes=15)
            readings.add(datetime.combine(change_date, datetime.min.time()).replace(hour=7))
            readings.add(datetime.combine(change_date, datetime.min.time()).replace(minute=30))
            rows.append({
                "t": minutes(t),
                "before": int(before.total_seconds() // 60),
                "after": int(after.total_seconds() // 60),
                "changeDate": change_date.isoformat(),
                "rplan": [[minutes(w), minutes(planned(w, zone, before, after))]
                          for w in sorted(readings)],
            })
            count += 1
        if rows:
            zones[name] = rows
    json.dump({
        "generator": "scripts/gen_dst_fixture.py",
        "source": "Python zoneinfo (system tzdata)",
        "tzdata": tzdata_version(),
        "from": START.isoformat(),
        "to": END.isoformat(),
        "units": "minutes since the Unix epoch; readings as wall minutes "
                 "(their digits read as UTC); offsets in minutes",
        "zoneCount": len(zones),
        "transitionCount": count,
        "zones": zones,
    }, sys.stdout, separators=(",", ":"), sort_keys=True)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
