#!/usr/bin/env python3
"""docs/TODO.md T-213 (N4): generate the in-app list of the Java/Kotlin
libraries that ship inside the APK, from the CycloneDX SBOM `:app:cyclonedxBom`
already produces (scoped to `releaseRuntimeClasspath` plus
`coreLibraryDesugaring` in android/app/build.gradle.kts).

Flutter's own licence collector ("Third-Party Licenses" on the About page) only
reads Dart packages' LICENSE files; it never sees AndroidX, Kotlin, Guava,
media3 or desugar_jdk_libs, which Gradle adds on its own. Apache-2.0 §4 asks
for a copy of the licence and the NOTICE text, BSD-3-Clause and GPL-2.0 for
the licence text with the binary. This list names each library, its version
and licence; the licence texts themselves are bundled separately (see
LICENCE_TEXTS below) and shown by lib/utils/licence_notices.dart.

Usage:
  python3 scripts/gen_android_library_notices.py <bom.json> > assets/text/licences/AndroidLibraries.txt
  python3 scripts/gen_android_library_notices.py <bom.json> --check assets/text/licences/AndroidLibraries.txt
  python3 scripts/gen_android_library_notices.py --self-test

`--check` exits 1 when the committed list differs from what the SBOM says
(ci.yml's build-android-release and release.yml run it right after the SBOM
is generated, so the shipped list cannot drift from the shipped libraries).
Regenerate locally with:
  (cd android && ./gradlew :app:cyclonedxBom)
  python3 scripts/gen_android_library_notices.py build/app/reports/cyclonedx/bom.json \
      > assets/text/licences/AndroidLibraries.txt

The generator also exits 1 when a library carries no licence at all, or a
licence for which LICENCE_TEXTS does not say where the app shows its text:
a new licence family arriving through a plugin is a licence decision, and
should stop the build until someone has looked at it.
"""
import difflib
import json
import sys

# Where the app shows each licence's full text. A licence id missing here
# fails generation - add it only together with the text it points to.
LICENCE_TEXTS = {
    "Apache-2.0": (
        "the full text is reproduced in \"Native Code Notices\" (zxing-cpp "
        "section) and under many Dart packages in \"Third-Party Licenses\"."
    ),
    "BSD-3-Clause": (
        "the 3-clause BSD text, with the copyright line of Protocol Buffers "
        "(repackaged as androidx.datastore:datastore-preferences-external-"
        "protobuf), is listed under \"Protocol Buffers\" in \"Third-Party "
        "Licenses\"."
    ),
    "GPL-2.0-with-classpath-exception": (
        "the full text (GPL-2.0 with the Classpath Exception) is listed under "
        "\"desugar_jdk_libs\" in \"Third-Party Licenses\"; the source code is "
        "published at https://github.com/google/desugar_jdk_libs."
    ),
}

HEADER = """\
ANDROID (JAVA/KOTLIN) LIBRARIES
===============================

docs/TODO.md T-213: besides the Dart packages listed under "Third-Party
Licenses", the Android build adds Java/Kotlin libraries of its own
(AndroidX, Kotlin, Guava, media3, desugar_jdk_libs, ...). Flutter's licence
collector cannot see them, so they are listed here.

Generated by scripts/gen_android_library_notices.py from the CycloneDX SBOM
of the release build (releaseRuntimeClasspath + coreLibraryDesugaring). Do
not edit by hand; CI fails when this list and the build disagree.

Not listed: the Flutter engine (io.flutter:*) and the Flutter plugins' own
Android modules - both are covered by their Dart packages' entries under
"Third-Party Licenses".
"""


def _is_listed(component: dict) -> bool:
    purl = component.get("purl") or ""
    if "project_path=" in purl:
        return False  # a Flutter plugin's own Gradle subproject
    if (component.get("group") or "") == "io.flutter":
        return False  # Flutter engine artifacts
    return component.get("type", "library") == "library"


def _licence_ids(component: dict) -> list[str]:
    ids = []
    for entry in component.get("licenses", []):
        if "expression" in entry:
            ids.append(entry["expression"])
            continue
        licence = entry.get("license", {})
        ids.append(licence.get("id") or licence.get("name") or "")
    return [i for i in ids if i]


class GenerationError(Exception):
    pass


def generate(bom: dict) -> str:
    rows = []
    problems = []
    used = set()
    for component in bom.get("components", []):
        if not _is_listed(component):
            continue
        coordinate = f"{component.get('group', '')}:{component.get('name', '')}"
        ids = _licence_ids(component)
        if not ids:
            problems.append(f"{coordinate}: no licence in the SBOM")
        for licence in ids:
            if licence not in LICENCE_TEXTS:
                problems.append(f"{coordinate}: licence {licence!r} has no "
                                "entry in LICENCE_TEXTS")
        used.update(ids)
        rows.append(f"{coordinate} {component.get('version', '')} - "
                    f"{' AND '.join(ids)}")
    if problems:
        raise GenerationError("\n".join(problems))

    rows = sorted(set(rows))
    out = [HEADER, f"{len(rows)} libraries:", ""]
    out.extend(f"  {row}" for row in rows)
    out.append("")
    out.append("Licence texts:")
    out.append("")
    for licence in sorted(used):
        out.append(f"  {licence}: {LICENCE_TEXTS[licence]}")
    out.append("")
    return "\n".join(out)


def _load(path: str) -> dict:
    with open(path) as f:
        return json.load(f)


def check(bom: dict, asset_path: str) -> int:
    expected = generate(bom)
    with open(asset_path) as f:
        actual = f.read()
    if actual == expected:
        print(f"{asset_path} matches the SBOM.")
        return 0
    print(f"{asset_path} is stale - it does not match the SBOM. Regenerate it "
          "with scripts/gen_android_library_notices.py (see its docstring).")
    sys.stdout.writelines(difflib.unified_diff(
        actual.splitlines(keepends=True), expected.splitlines(keepends=True),
        fromfile=asset_path, tofile="generated from SBOM"))
    return 1


def self_test() -> int:
    import os
    import tempfile

    failed = False

    def fail(message: str) -> None:
        nonlocal failed
        print(f"SELF-TEST FAIL: {message}")
        failed = True

    def lib(group, name, version, *ids, purl=None):
        return {
            "type": "library", "group": group, "name": name,
            "version": version,
            "purl": purl or f"pkg:maven/{group}/{name}@{version}",
            "licenses": [{"license": {"id": i}} for i in ids],
        }

    bom = {"components": [
        lib("androidx.core", "core", "1.18.0", "Apache-2.0"),
        lib("com.android.tools", "desugar_jdk_libs", "2.1.5",
            "GPL-2.0-with-classpath-exception"),
        lib("androidx.camera", "camera-core", "1.6.2", "Apache-2.0",
            "BSD-3-Clause"),
        # Must be left out: a plugin's own subproject and the engine.
        lib("io.flutter.plugins.imagepicker", "image_picker_android",
            "1.0-SNAPSHOT",
            purl="pkg:maven/x/y@1.0?project_path=%3Aimage_picker_android"),
        lib("io.flutter", "flutter_embedding_release", "1.0.0-abc"),
    ]}
    try:
        text = generate(bom)
    except GenerationError as e:
        print(f"SELF-TEST FAIL: generate() rejected a valid BOM: {e.args[0]}")
        print("SELF-TEST: FAILED")
        return 1
    for wanted in ("  androidx.core:core 1.18.0 - Apache-2.0",
                   "  com.android.tools:desugar_jdk_libs 2.1.5 - "
                   "GPL-2.0-with-classpath-exception",
                   "  androidx.camera:camera-core 1.6.2 - Apache-2.0 AND "
                   "BSD-3-Clause",
                   "3 libraries:",
                   "  GPL-2.0-with-classpath-exception: "):
        if wanted not in text:
            fail(f"generated text lacks {wanted!r}")
    for unwanted in ("image_picker_android", "flutter_embedding_release"):
        if unwanted in text:
            fail(f"generated text lists {unwanted!r}")
    lines = [line for line in text.splitlines() if line.startswith("  andr")
             or line.startswith("  com.")]
    if lines != sorted(lines):
        fail("libraries are not sorted")
    if generate(bom) != generate({"components": bom["components"][::-1]}):
        fail("output depends on the SBOM's component order")

    # A library without a licence, or with an unmapped one, stops generation.
    for label, component in (
            ("no licence", lib("com.example", "nolicence", "1")),
            ("unmapped licence", lib("com.example", "epl", "1", "EPL-2.0"))):
        try:
            generate({"components": [component]})
            fail(f"{label}: generation did not fail")
        except GenerationError:
            pass

    # --check: identical asset passes, a stale one (version bump) fails.
    tmpdir = tempfile.mkdtemp()
    asset = os.path.join(tmpdir, "AndroidLibraries.txt")
    with open(asset, "w") as f:
        f.write(text)
    if check(bom, asset) != 0:
        fail("check() rejected a freshly generated asset")
    bumped = json.loads(json.dumps(bom))
    bumped["components"][0]["version"] = "1.19.0"
    if check(bumped, asset) != 1:
        fail("check() accepted a stale asset after a version bump")

    if failed:
        print("SELF-TEST: FAILED")
        return 1
    print("SELF-TEST: all cases passed.")
    return 0


def main(argv: list[str]) -> int:
    if argv[:1] == ["--self-test"]:
        return self_test()
    if len(argv) == 1:
        try:
            sys.stdout.write(generate(_load(argv[0])))
        except GenerationError as e:
            print(f"Cannot generate the notice list:\n{e.args[0]}",
                  file=sys.stderr)
            return 1
        return 0
    if len(argv) == 3 and argv[1] == "--check":
        try:
            return check(_load(argv[0]), argv[2])
        except GenerationError as e:
            print(f"Cannot generate the notice list:\n{e.args[0]}")
            return 1
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
